count shower component completed
Efekahya/rnmclient pull request #10
Opened 2022-07-28 13:07 UTC by Efekahya

![resim](https://user-images.githubusercontent.com/75262924/181512504-b76f34b2-9a5e-4580-a436-71da7aa6f2a9.png)
https://www.figma.com/file/SBPCNjmePIwJCzqqhXF9Y8/Rick-and-Morty---Digieggs-Assessment?node-id=1019%3A10331

2022-07-28 13:14 UTC, bybash requested changes

2022-07-28 13:14 UTC, bybash commented on src/components/ShowCount/styles.scss
> +.container {
I think you need to use some specific names for your CSS classes to not overwrite each other.

2022-07-28 13:34 UTC, iremlaya commented on src/components/ShowCount/index.tsx
> +export default function ShowCount({
new line

2022-07-29 08:55 UTC, iremlaya approved these changes

2022-07-29 12:16 UTC, merged