CharacterList component created
Efekahya/rnmclient pull request #3
Opened 2022-07-24 15:06 UTC by Efekahya

2022-07-25 11:31 UTC, isatanis requested changes

2022-07-25 11:31 UTC, isatanis commented on src/components/CharacterList/index.tsx
> +    <>
unnecessary fragment

2022-07-25 11:31 UTC, isatanis commented on src/components/CharacterList/index.tsx
> +  }
you shouldn't try to update a prop. if you need a new variable, just define it.

2022-07-25 11:31 UTC, isatanis commented on src/components/CharacterList/index.tsx
> +interface CharacterListProps {
we're adding `I` to beginning of the interfaces. change it to `ICharacterListProps`

2022-07-25 11:31 UTC, isatanis commented on src/components/CharacterList/styles.scss
> +    display: inline-grid;
use flex instead of grid.

2022-07-25 11:31 UTC, isatanis commented on src/components/CharacterList/index.tsx
> -import "./styles.scss"
why did you remove the styles?

2022-07-25 11:31 UTC, isatanis commented on src/components/CharacterList/index.tsx
> +        {characters.map((character) => (
use destructuring if there is no complex things in the function.

2022-07-26 09:54 UTC, bybash requested changes
Nice 👍 Added some comments.

2022-07-26 09:54 UTC, bybash commented on src/App.tsx
> +  }
Don't define interface or type inside the components. If you want to define them in the same file, define them at the top before the component definition. Also, you can define them in a separate type file and then export and use it wherever you want.

2022-07-26 09:54 UTC, bybash commented on src/App.tsx
> +  const character: ICharacter = {
You can define them in a mock file and then you can import it and use it.

2022-07-26 09:54 UTC, bybash commented on src/components/CharacterList/index.tsx
> +  characters: ICharacter[] //TODO Characterler objesi gelince character tipi ile değiştirilecek
Please write your comments in English.

2022-07-26 09:54 UTC, bybash commented on src/components/CharacterList/index.tsx
> +  }
Need an else block, otherwise sliced will be undefined.

2022-07-26 09:54 UTC, bybash commented on src/index.tsx
> +import App from "./App"
Try to order your imports.
Import order:
1) Third parties
2) Component
3) Utilities, helper functions
4) Images
5) Styles

2022-07-26 09:54 UTC, bybash commented on src/index.tsx
> +import reportWebVitals from "./reportWebVitals"
I don't think we need reportWebVitals you can remove it.

2022-07-26 09:54 UTC, bybash commented on src/styles.scss
> +@import "./components/CharacterList/styles.scss";
Import component styles inside components' own file, no need to import all of them here.

2022-07-28 12:39 UTC, bybash approved these changes

2022-07-29 14:33 UTC, iremlaya approved these changes

2022-07-29 14:43 UTC, merged