Navigation component
Efekahya/rnmclient pull request #6
Opened 2022-07-26 06:52 UTC by Efekahya

2022-07-26 10:26 UTC, bybash requested changes
👍 noted down some comments.

2022-07-26 10:26 UTC, bybash commented on src/components/Navigation/index.tsx
> +        }
Make these operations before render function.

2022-07-26 10:26 UTC, bybash commented on src/App.tsx
> +      </BrowserRouter>
You don't need to send this kind of change in your PRs. Make your tests in your local and don't push them inside the PRs.

2022-07-28 13:02 UTC, bybash requested changes

2022-07-28 13:02 UTC, bybash commented on src/components/Navigation/index.tsx
> +        }
Create an array of URLs which you will give to the `<a>` tag before the render method and then just render.
```suggestion
var urlsArray = href.map((item) => {
         for (let i = 0; i < href.length; i++) {
           if (href[i] === item) {
             if (i === 0) {
               temp = href[0]
             } else {
               temp = href.slice(0, i + 1).join("/")
             }
           }
         }

      {urlsArray.map((item, index) => (
           <>
             <div key={index} className="navigationText">
               <a href={"/" + item}>{hrefUpper[index]}</a>
             </div>
             <RightArrow />
           </>
        )
       }
```

2022-08-01 10:44 UTC, loneddonkey requested changes

2022-08-01 10:44 UTC, loneddonkey commented on src/components/Navigation/index.tsx
> +    temp += "/" + url
```suggestion
    temp += `/ ${url}`
```

2022-08-01 10:44 UTC, loneddonkey commented on src/components/Navigation/index.tsx
> +      <a href={"/" + url}>{hrefUpper[index]}</a>
```suggestion
      <a href={`/ ${url}`}>{hrefUpper[index]}</a>
```

2022-08-01 10:44 UTC, loneddonkey commented on src/components/Navigation/styles.scss
> +    color: #808080;
I recommend variable here.

2022-08-02 07:16 UTC, merged