characterDetailCard completed
Efekahya/rnmclient pull request #8
Opened 2022-07-28 09:52 UTC by Efekahya

<img width="385" alt="resim" src="https://user-images.githubusercontent.com/75262924/181477146-078c20ef-4de6-4ac7-b92b-e5aece913466.png">

https://www.figma.com/file/SBPCNjmePIwJCzqqhXF9Y8/Rick-and-Morty---Digieggs-Assessment?node-id=1014%3A910

2022-07-28 13:04 UTC, bybash requested changes
Looks good, I made one comment otherwise good to go.

2022-07-28 13:04 UTC, bybash commented on src/App.tsx
> +      <CharacterDetailCard title="Gender" content="Male" />
Don't push this changes

2022-07-28 13:08 UTC, bybash requested changes

2022-07-28 13:08 UTC, bybash commented on src/components/CharacterDetailCard/styles.scss
> +    height: 81px;
I couldn't be sure about these two. 
Do you need to set the height? 
For width maybe max-width can be used here.

2022-07-29 08:56 UTC, iremlaya approved these changes

2022-07-29 12:18 UTC, merged